# Uptime Monitor Configuration

settings:
  title: "服务监控"
  logo: "https://snean.eu.cc/images/asset/favicon/favicon.svg?original=true&v=1781317835" # Optional: URL to your logo image
  callback_url: ""
  callback_secret: ""
  # If true, only send notifications when status changes to DOWN.
  # DEGRADED or UP (recovery) events will NOT trigger notifications.
  notification_on_down_only: true 
  tags:
    - id: "cfw"
      label: "Cloudflare Worker"
      color: "#D97706"

    - id: "monitor"
      label: "监控"
      color: "#D97707"
incidents:

    
groups:
  - id: "my_services"
    name: "My Services"
    monitors:
      - id: "uptimekuma"
        name: "UptimeKuma"
        tags: [monitor]
        type: "http"
        url: "https://snean.eu.cc/monitor"
        method: "HEAD"
        timeout: 60000
        expected_latency: 1000
        grace_period: 3
        display:
          chart: true
          public_link: true
        validation:
          status: 200

      - id: "blog_cf"
        name: "博客"
        tags: [cfw]
        type: "http"
        url: "https://snean.eu.cc/"
        method: "HEAD"
        timeout: 60000
        expected_latency: 1000
        grace_period: 3
        display:
          chart: true
          public_link: true
        validation:
          status: 200
